name: 更新日志

on:
  release:
    types: [published]  # 仅在正式发布时触发

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 明确检出主分支（例如 main 或 master）
          ref: main
          persist-credentials: true

      - name: Get release notes content
        id: release-notes
        run: |
          # 使用随机边界避免冲突
          RANDOM_EOF=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 16)
          echo "notes<<$RANDOM_EOF" >> $GITHUB_ENV
          echo "${{ github.event.release.body }}" >> $GITHUB_ENV
          echo "$RANDOM_EOF" >> $GITHUB_ENV

      - name: Write to updatelog.md
        run: |
          # 安全写入文件
          printf "%s\n" "${{ env.notes }}" > updatelog.md
          cat updatelog.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 添加更改并提交
          git add updatelog.md
          git commit -m "Update release notes from release ${{ github.event.release.tag_name }}"
          
          # 推送到主分支
          git push origin main
