#!/bin/bash

BASE_PATH="/storage/emulated/0/Flyme/icon"
TARGET_PATH="/storage/emulated/0//Flyme/icons"
FINAL_LOCATION="/storage/emulated/0/"

# 第一部分黑名单
BLACKLIST_PART1=(
    "idm.internet.download.manager.plus*"
)

# 第二部分黑名单
BLACKLIST_PART2=(
    "*_bg.png"
    "*air.jp.globalgear.fam*"
    "*app.huawei.auto*"
    "*app.landrop.landrop_flutter*"
    "*background*"
    "*balti.xposed.pixelifygooglephotos*"
    "*bf.sgs.hdexp*"
    "*ch.want.imagecompare*"
    "*cn.com.hkgt.gasapp*"
    "*cn.deepink.reader*"
    "*cn.ninebot.ninebot*"
    "*cn.nr19.mbrowser*"
    "*cn.xihan.age*"
    "*com.android.alarmclock*"
    "*com.appbyme.app284211*"
    "*com.autonavi.minimap*"
    "*com.chanyouji.birth*"
    "*com.ChillyRoom.DungeonShooter*"
    "*com.clover.daysmatter*"
    "*com.cmplay.tiles2_cn.m4399*"
    "*com.dahua.leapmotor*"
    "*com.domosekai.cardreader*"
    "*com.doumi.jianzhi*"
    "*com.ea.gp.apexlegendsmobilefps*"
    "*com.elpatrixf.OuO*"
    "*com.example.bwappdoor*"
    "*com.fungames.sniper3d*"
    "*com.funnygames.darknote*"
    "*com.funnygames.escape.zjy4*"
    "*com.gameabc.sgspad*"
    "*com.github.haocen2004.bh3_login_simulation*"
    "*com.google.android.apps.translate*"
    "*com.graymatrix.did*"
    "*com.handwriting.makefont*"
    "*com.happyelements.AndroidAnimal*"
    "*com.hegu.dnl.mi*"
    "*com.hexin.plat.android*"
    "*com.hihanhan.one*"
    "*com.HoYoverse.Nap*"
    "*com.huxiu*"
    "*com.icloudoor.bizranking*"
    "*com.ilongyuan.cytus.ly*"
    "*com.ioncannon.cpuburn.gpugflops*"
    "*com.ioncannon.memlatency*"
    "*com.jasperhale.onetapdoze*"
    "*com.jd.paipai.ppershou*"
    "*com.jiansheng.blmn.bilibili*"
    "*com.knight.union.mi*"
    "*com.kooapps.pianotiles2gp*"
    "*com.kuangxiangciweimao.novel*"
    "*com.kulya.clock*"
    "*com.kurogame.mingchao*"
    "*com.leiting.aobi*"
    "*com.leiting.apart*"
    "*com.leiting.bouken2*"
    "*com.leiting.daluandou.mi*"
    "*com.leiting.depart2*"
    "*com.leiting.dungeon3*"
    "*com.leiting.elves2*"
    "*com.leiting.gamedev3*"
    "*com.leiting.mole.aligames*"
    "*com.leiting.ninja*"
    "*com.leiting.noodle*"
    "*com.leiting.onsen2*"
    "*com.leiting.pirate*"
    "*com.leiting.resort*"
    "*com.leiting.restaurant*"
    "*com.leiting.school2*"
    "*com.leiting.soccer*"
    "*com.leiting.themepark*"
    "*com.leiting.turmoil*"
    "*com.leiting.wf*"
    "*com.leiting.xian*"
    "*com.leiting.zaibatu3*"
    "*com.lelaer.yshelper*"
    "*com.lemon.lvoverseas*"
    "*com.lengtong.tool*"
    "*com.lerdong.dm78*"
    "*com.liming.refreshrate*"
    "*com.lilithgames.xgame.android.cn*"
    "*com.miHoYo.GenshinImpact*"
    "*com.miHoYo.Nap*"
    "*com.miHoYo.bh3.uc*"
    "*com.miHoYo.cloudgames.hkrpg*"
    "*com.miHoYo.cloudgames.ys*"
    "*com.miHoYo.enterprise.NGHSoD*"
    "*com.miHoYo.hkrpg*"
    "*com.miHoYo.ys.bilibili*"
    "*com.miHoYo.ys.mi*"
    "*com.miHoYo.Yuanshen*"
    "*com.mojang.minecraftpe*"
    "*com.mubu.app*"
    "*com.nasoft.socmark*"
    "*com.netease.dwrg*"
    "*com.netease.g104.cn*"
    "*com.netease.g93na*"
    "*com.netease.harrypoter*"
    "*com.netease.hyxd*"
    "*com.netease.hyxd.aligames*"
    "*com.netease.hyxd.mi*"
    "*com.netease.idol2*"
    "*com.netease.jddsaef*"
    "*com.netease.jddsaef.mi*"
    "*com.netease.l22*"
    "*com.netease.mc.aligames*"
    "*com.netease.mc.mi*"
    "*com.netease.mctest*"
    "*com.netease.mduel*"
    "*com.netease.mrzh*"
    "*com.netease.nshm*"
    "*com.netease.onmyoji*"
    "*com.netease.race*"
    "*com.netease.sdsbq*"
    "*com.NextFloor.phdiver*"
    "*com.nn.cowtransfer*"
    "*com.omarea.vtools*"
    "*com.pingan.carowner*"
    "*com.popcap.pvz*"
    "*com.prpr.musedash*"
    "*com.prpr.musedash.TapTap*"
    "*com.PigeonGames.Phigros*"
    "*com.qcymall.earphonesetup*"
    "*com.qixin.mihuas*"
    "*com.qqgame.hlddz*"
    "*com.qun1044355230.mxhz*"
    "*com.qun1044355230.mxzq*"
    "*com.raincat.unblockmusicpro*"
    "*com.realcloud.loochadroid.college*"
    "*com.rfidresearchgroup.rfidtools*"
    "*com.ruanmei.zuihuimai*"
    "*com.sankuai.meituan*"
    "*com.samsung.android.ruler*"
    "*com.sega.pjsekai*"
    "*com.semeevs.driftyrace3d*"
    "*com.shugi.controller*"
    "*com.shuqi.controller*"
    "*com.smilingmobile.seekliving*"
    "*com.snda.lantern.wifilocating*"
    "*com.ss.android.article.lite*"
    "*com.ss.android.ugc.aweme.lite*"
    "*com.sug3rs.manypaper*"
    "*com.taobao.idlefish*"
    "*com.tencent.blackkey*"
    "*com.tencent.fvb*"
    "*com.tencent.game.rhythmmaster*"
    "*com.tencent.game.VXDGame*"
    "*com.tencent.gamehelper.pg*"
    "*com.tencent.gamehelper.smoba*"
    "*com.tencent.ig*"
    "*com.tencent.igame*"
    "*com.tencent.igce*"
    "*com.tencent.iglite*"
    "*com.tencent.KiHan*"
    "*com.tencent.mf.uam*"
    "*com.tencent.nfsonline*"
    "*com.tencent.pocket*"
    "*com.tencent.ryxsg*"
    "*com.tencent.tmgp.bh3*"
    "*com.tencent.tmgp.cf*"
    "*com.tencent.tmgp.cod*"
    "*com.tencent.tmgp.codev*"
    "*com.tencent.tmgp.gnyx*"
    "*com.tencent.tmgp.projectg*"
    "*com.tencent.tmgp.pubgmhd*"
    "*com.tencent.tmgp.qqx5*"
    "*com.tencent.tmgp.sgame*"
    "*com.tencent.tmgp.speedmobile*"
    "*com.tencent.tmgp.supercell.clashofclans*"
    "*com.tencent.tmgp.wdsj666*"
    "*com.tencent.toaa*"
    "*com.tianxingjia.feibotong*"
    "*com.twitter.android*"
    "*com.uanmi.miaojiaccount*"
    "*com.wangc.bill*"
    "*com.wemomo.pott*"
    "*com.wewin.wewinprinterprofessional*"
    "*com.wondertek.paper*"
    "*com.wumii.android.athena*"
    "*com.xd.cfbmf*"
    "*com.xfdm.app*"
    "*com.xiaomi.o2o*"
    "*com.xiaomi.wearable*"
    "*com.ysy.switcherfiveg*"
    "*com.yunda.app*"
    "*com.zerotier.one*"
    "*com.zhenxi.hunter*"
    "*com.wemomo.pott*"
    "*fun.upup.musicfree*"
    "*idm.internet.download.manager.plus*"
    "*jackpal.androidterm*"
    "*me.tigerhix.cytoid.cn*"
    "*moe.low.arc*"
    "*net.xrcloud*"
    "*net.xrcloud*"
    "*one.hh.oneclient*"
    "*org.epcdiy.memory*"
    "*org.epcdiy.memory*"
    "*org.flos.phira*"
    "*org.izyz*"
    "*rocket.service.super*"
    "*rocket.service.super*"
    "*so.ofo.labofo*"
    "*so.ofo.labofo*"
    "*wallhaven.top*"
    "*wallhaven.top*"
    "*www.right.com.cn*"
    "*www.right.com.cn*"
    "*xzr.hkf*"
    "*xzr.konabess*"
    "*xzr.perfmon*"
    "*xzr.perfmon*"
)

# 检查BASE_PATH是否存在
if [ ! -d "$BASE_PATH" ]; then
    echo "注意：目录 $BASE_PATH不存在，自动创建并退出。"
    mkdir -p "$BASE_PATH"
    exit 0
fi

# 确保目标文件夹存在
mkdir -p "$TARGET_PATH"

# 初始化计数器
RENAME_COUNT=0

# 处理文件重命名和移动
for DIR in "$BASE_PATH"/*/; do
    DIR_NAME=$(basename "$DIR")
    
    if [ -e "$DIR/0.png" ] && [ -e "$DIR/1.png" ]; then
        mv "$DIR/0.png" "$TARGET_PATH/${DIR_NAME}_bg.png"
        mv "$DIR/1.png" "$TARGET_PATH/${DIR_NAME}_fg.png"
        
        RENAME_COUNT=$((RENAME_COUNT + 1))
        echo "重命名第$RENAME_COUNT个: $DIR_NAME"
        rmdir "$DIR" 2>/dev/null
    else
        echo "在 $DIR找不到0.png和1.png"
    fi
done

echo "操作完成"
echo "成功重命名: $RENAME_COUNT个目录"

# 通用压缩函数
compress_files() {
    local zip_name="$1"
    local exclude_list=("${@:2}")
    local exclude_params=()
    
    for pattern in "${exclude_list[@]}"; do
        exclude_params+=(-x "$pattern")
    done
    
    cd "$TARGET_PATH" || return 1
    zip -0 -r "$zip_name" . "${exclude_params[@]}" >/dev/null
    mv "$zip_name" "$FINAL_LOCATION"
}

# 第一部分压缩
compress_files "icons.zip" "${BLACKLIST_PART1[@]}" && \
echo "已创建压缩文件: $FINAL_LOCATION/icons.zip"

# 第二部分压缩
compress_files "icons_night.zip" "${BLACKLIST_PART2[@]}" && \
echo "已创建压缩文件: $FINAL_LOCATION/icons_night.zip"